#ifndef PE_PROB12_H
#define PE_PROB12_H

/*
The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
*/

internal inline u32 getDivisorCount(u64 n)
{
    u32 result = 0;

    u64 sqrtOfN = (u64) mathSquareRoot((f64) n);
    for (u64 i = 1; i <= sqrtOfN; ++i)
    {
        if (n % i == 0)
        {
            if (mathSquare(i) == n)
            {
                ++result;
            }
            else
            {
                result += 2;
            }
        }
    }

    return result;
}

SolveProblemFunc(12)
{
    u32 result = 0;

    u32 i = 1;

    getDivisorCount(60);

    for (;;)
    {
        u32 divisorCount = getDivisorCount(result);
        if (divisorCount > 500)
        {
            break;
        }
        else
        {
            result += i;
            ++i;
        }
    }

    ProblemWriteOutput("%d", result);
}

#endif
